[Model]
; Название бренда
vendor = HP

; Название модели
model = Pavilion dv6500

; Теги модели
keywords_string = Hewlett Packard, HP, Pavilion, dv6500, dv6620er, dv6470, dv6499, dv6501, dv6502, dv6503, dv6504, dv6505, dv65058, dv6507, dv6508, dv6509, dv6000, dv6200, dv6600, dv6700, dv6800, dv6900

; Страна производитель
manufacturer_country = Китай

; Класс качества
quality_class = Original

; Цвет
color = Черный

; Совместимость с брендом
; Acer, Alcatel, Apple, Asus, Dell, Fly, Fujitsu, Gateway/Packard Bell, HP (Hewlett Packard)
; IBM, Lenovo, LG, MSI, Panasonic, Prestigio, Samsung, Sony, Toshiba, Xiaomi
brand_compatibility = HP (Hewlett Packard)

; Материал корпуса
housing_material = Пластик

; Раскладка клавиатуры
keyboard_layout = Английская|Русская|Немецкая|Украинская

; Поверхность
; Варианты: "Глянцевая", "Матовая"
surface = Глянцевая

; Назначение
purpose = Для ноутбука

; Платформа
; Варианты: "Intel", "AMD"
platform = AMD

; Состояние ноутбука, принимает три состояния:
; "Б/У" - бывший в употреблении
; "Новый" - новый
; "Н" - состояние не указывается
state = Б/У

[Path]
; directory = F:\PC2\пром\
directory = D:\prom\
; directory = C:\work\naDetali\test\
all_photos_dir_name = _All Photos

[Hdd]
; Western Digital, Seagate
hdd_brand = Western Digital
hdd_model = WD5000BPVT
hdd_size = 500
