from settings import model_name

detail_names = [
    {
        "name_rus":'Петли (левая, правая) %s' % (model_name),
        "name_ukr":'Петлі (ліва, права) %s' % (model_name),
        "tags_rus":"петли, петля левая, петля правая, петля, петли матрицы, петли экрана, экран, матрица, крепление, часть корпуса",
        "tags_ukr":"петлі, петля ліва, петля права, петля, петлі матриці, петлі екрану, екран, матрица, кріплення, частина корпусу",
        "category":"Части корпуса ноутбука",
        "description_rus":"Петли почищены, сгибаются-разгибаются нормально.",
        "description_ukr":"Петлі почищені, згинаються-розгинаються нормально.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Петля левая (петли) %s' % (model_name),
        "name_ukr":'Петля ліва (петлі) %s' % (model_name),
        "tags_rus":"петли, петля левая, петля, петли матрицы, петли экрана, экран, матрица, крепление, часть корпуса",
        "tags_ukr":"петлі, петля ліва, петля, петлі матриці, петлі екрану, екран, матрица, кріплення, частина корпусу",
        "category":"Части корпуса ноутбука",
        "description_rus":"Петля почищена, сгибается-разгибается нормально.",
        "description_ukr":"Петля почищена, згинається-розгинається нормально.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Петля правая (петли) %s' % (model_name),
        "name_ukr":'Петля права (петлі) %s' % (model_name),
        "tags_rus":"петли, петля правая, петля, петли матрицы, петли экрана, экран, матрица, крепление, часть корпуса",
        "tags_ukr":"петлі, петля права, петля, петлі матриці, петлі екрану, екран, матрица, кріплення, частина корпусу",
        "category":"Части корпуса ноутбука",
        "description_rus":"Петля почищена, сгибается-разгибается нормально.",
        "description_ukr":"Петля почищена, згинається-розгинається нормально.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Нижняя часть корпуса %s (низ, дно, поддон, корыто)' % (model_name),
        "name_ukr":'Нижня частина корпуса %s (низ, дно, піддон, корито)' % (model_name),
        "tags_rus":"нижняя крышка базы, нижняя часть корпуса, дно, днище, нижняя крышка базы, корито, нижний корпус, низ, поддон",
        "tags_ukr":"нижня кришка бази, нижня частина корпуса, дно, днище, нижняя крышка базы, корито, нижній корпус, низ, піддон",
        "category":"Части корпуса ноутбука",
        "description_rus":"Дно корпуса вымыто и почищено.",
        "description_ukr":"Дно корпуса вимито та почищено.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Крышка матрицы %s (крышка экрана, дисплея)' % (model_name),
        "name_ukr":'Кришка матриці %s (крышка екрану, дисплею)' % (model_name),
        "tags_rus":"кришка матрицы, крышка экрана, корпус экрана, корпус, корпус ноутбука, задняя крышка экрана",
        "tags_ukr":"кришка матриці, кришка екрану, корпус екрану, корпус, корпус ноутбука, корпус ноутбуку, задня кришка екрану",
        "category":"Части корпуса ноутбука",
        "description_rus":"Крышка матрицы вымыта и почищена.",
        "description_ukr":"Кришка матриці вымита та почищена.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Рамка матрицы (дисплея) %s' % (model_name),
        "name_ukr":'Рамка матриці (дисплею) %s' % (model_name),
        "tags_rus":"рамка матрицы, рамка экрана, рамка дисплея",
        "tags_ukr":"рамка матриці, рамка екрану, рамка дисплея, рамка дисплею",
        "category":"Части корпуса ноутбука",
        "description_rus":"Рамка матрицы вымыта и почищена.",
        "description_ukr":"Рамка матриці вимита та почищена.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Панель с кнопками %s' % (model_name),
        "name_ukr":'Панель з кнопками %s' % (model_name),
        "tags_rus":"панель кнопок, верхняя панель, панель кнопки включения, панель, панель с кнопками, панель питания",
        "tags_ukr":"панель кнопок, верхня панель, панель кнопки включення, панель, панель кнопки живлення, панель з кнопками, панель живлення",
        "category":"Части корпуса ноутбука",
        "description_rus":"Панель вымыта и почищена.",
        "description_ukr":"Панель вимита та почищена.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Панель кнопки включения %s (вкл/выкл)' % (model_name),
        "name_ukr":'Панель кнопки включення (живлення) %s (вкл/викл)' % (model_name),
        "tags_rus":"панель кнопки включения, панель, панель с кнопками, панель питания",
        "tags_ukr":"панель кнопки включення, панель, панель кнопки живлення, панель з кнопками, панель живлення",
        "category":"Части корпуса ноутбука",
        "description_rus":"Панель вымыта и почищена.",
        "description_ukr":"Панель вимита та почищена.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Заглушки (крышки) петель %s' % (model_name),
        "name_ukr":'Заглушки (крышки) петель %s' % (model_name),
        "tags_rus":"колпачки, заглушки (крышки) петель, заглушки, заглушка, петли, петля",
        "tags_ukr":"ковпачки, заглушки (крышки) петель, заглушки, заглушка, петлі, петля",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Накладка на петли %s' % (model_name),
        "name_ukr":'Накладка на петлі %s' % (model_name),
        "tags_rus":"накладка, накладка на петли, петля, петли, колпачки, заглушки, заглушка",
        "tags_ukr":"накладка, накладка на петлі, петля, петлі, ковпачки, заглушки, заглушка",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Тачпад (трекпад) %s (touchpad)' % (model_name),
        "name_ukr":'Тачпад (трекпад) %s (touchpad)' % (model_name),
        "tags_rus":"Плата тачпад, тачпад, touchpad, трекпад",
        "tags_ukr":"Плата тачпад, тачпад, touchpad, трекпад",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Панель тачпада (трекпада) %s' % (model_name),
        "name_ukr":'Панель тачпада (трекпада) %s' % (model_name),
        "tags_rus":"панель тачпада, тачпад, touchpad",
        "tags_ukr":"панель тачпада, тачпад, touchpad",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата, шлейф, кнопки тачпада %s (touchpad)' % (model_name),
        "name_ukr":'Плата, шлейф, кнопки тачпаду %s (touchpad)' % (model_name),
        "tags_rus":"Плата, шлейф, кнопки тачпада, (touchpad)",
        "tags_ukr":"Плата, шлейф, кнопки тачпаду, (touchpad)",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата, кнопки тачпада %s (touchpad)' % (model_name),
        "name_ukr":'Плата, кнопки тачпаду %s (touchpad)' % (model_name),
        "tags_rus":"touchpad, плата, кнопки тачпада",
        "tags_ukr":"touchpad, плата, кнопки тачпаду",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Сервисная крышка корпуса %s (заглушка)' % (model_name),
        "name_ukr":'Сервісна кришка корпусу %s (заглушка)' % (model_name),
        "tags_rus":"сервисная крышка, крышка, заглушка, крышка корпуса",
        "tags_ukr":"сервісна кришка, кришка, заглушка, кришка корпусу",
        "category":"Части корпуса ноутбука",
        "description_rus":"Сервисная крышка вымыта и почищена.",
        "description_ukr":"Сервісна кришка вимита та почищена.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Сервисная крышка HDD/SSD %s' % (model_name),
        "name_ukr":'Сервісна кришка HDD/SSD %s' % (model_name),
        "tags_rus":"сервисная крышка, крышка, hdd, ssd, hdd/ssd, заглушка",
        "tags_ukr":"сервісна кришка, кришка, hdd, ssd, hdd/ssd, заглушка",
        "category":"Части корпуса ноутбука",
        "description_rus":"Сервисная крышка вымыта и почищена.",
        "description_ukr":"Сервісна кришка вимита та почищена.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Сервисная крышка охлаждение %s' % (model_name),
        "name_ukr":'Сервісна кришка охолодження %s' % (model_name),
        "tags_rus":"сервисная крышка, крышка, охлаждение, заглушка",
        "tags_ukr":"сервісна кришка, кришка, охолодження, заглушка",
        "category":"Части корпуса ноутбука",
        "description_rus":"Сервисная крышка вымыта и почищена.",
        "description_ukr":"Сервісна кришка вимита та почищена.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Клавиатура %s' % (model_name),
        "name_ukr":'Клавіатура %s' % (model_name),
        "tags_rus":"клавиатура, клава, keyboard",
        "tags_ukr":"клавіатура, клава, keyboard",
        "category":"Клавиатурные блоки для ноутбуков",
        "description_rus":"Клавиатура вымыта, почищена, протестирована специальным прибором. Все кнопки работают и не имеют хруста.",
        "description_ukr":"Клавіатура вимита, почищена, протестована спеціальним прибором. Всі кнопки працюють та не мають хрусту.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Рамка клавиатуры %s' % (model_name),
        "name_ukr":'Рамка клавіатури %s' % (model_name),
        "tags_rus":"рамка клавиатуры, рамка, клавиатура, клава, keyboard",
        "tags_ukr":"рамка клавіатури, рамка, клавіатура, клава, keyboard",
        "category":"Части корпуса ноутбука",
        "description_rus":"Рамка вымыта и почищена.",
        "description_ukr":"Рамка вимита та почищена.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Шлейф клавиатуры %s (keyboard)' % (model_name),
        "name_ukr":'Шлейф клавіатури %s (keyboard)' % (model_name),
        "tags_rus":"шлейф клавиатуры, шлейф, клавиатура, клава, keyboard",
        "tags_ukr":"шлейф клавіатури, шлейф, клавіатура, клава, keyboard",
        "category":"Шлейфы и разъемы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },

    {
        "name_rus":'Материнская плата %s (Системная плата)' % (model_name),
        "name_ukr":'Материнська плата %s (Системна плата)' % (model_name),
        "tags_rus":"материнская плата, системная плата",
        "tags_ukr":"материнська плата, системна плата",
        "category":"Материнские платы",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Материнская плата %s (Системная плата, нр)' % (model_name),
        "name_ukr":'Материнська плата %s (Системна плата, нп)' % (model_name),
        "tags_rus":"материнская плата, системная плата",
        "tags_ukr":"материнська плата, системна плата",
        "category":"Материнские платы",
        "description_rus":"<b>Внимание! Материнская плата не работает!</b> На детали или под восстановление.",
        "description_ukr":"<b>Увага! Материнська плата не працює!</b> На деталі або під відновлення.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Кулер, вентилятор %s (FAN)' % (model_name),
        "name_ukr":'Кулер, вентилятор %s (FAN)' % (model_name),
        "tags_rus":"кулер, вентилятор, fan",
        "tags_ukr":"кулер, вентилятор, fan",
        "category":"Системы охлаждения для ноутбуков",
        "description_rus":"Кулер почищен, вымыт, смазан специальной смазкой. Проверен, не шумит.",
        "description_ukr":"Кулер почищений, вимитий та змазаний спеціальною змазкою. Перевірений, не шумить.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Система охлаждения, термотрубка %s DIS' % (model_name),
        "name_ukr":'Система охолодження, термотрубка %s DIS' % (model_name),
        "tags_rus":"термотрубка, термотрубки, радиатор, система охлаждения, охлаждение, термотрубка системы охлаждения",
        "tags_ukr":"термотрубка, термотрубки, радіатор, система охолодження, охолодження, термотрубка системи охолодження",
        "category":"Кулеры и системы охлаждения",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Система охлаждения, термотрубка %s UMA' % (model_name),
        "name_ukr":'Система охолодження, термотрубка %s UMA' % (model_name),
        "tags_rus":"термотрубка, термотрубки, радиатор, система охлаждения, охлаждение, термотрубка системы охлаждения",
        "tags_ukr":"термотрубка, термотрубки, радіатор, система охолодження, охолодження, термотрубка системи охолодження",
        "category":"Кулеры и системы охлаждения",
        "description_rus":"Термотрубка проверена на теплопроводность - все в норме.",
        "description_ukr":"Термотрубка перевірена на теплопровідність - все в нормі.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Оптический привод DVD-RW %s' % (model_name),
        "name_ukr":'Оптичний привід DVD-RW %s' % (model_name),
        "tags_rus":"оптический привод, привод, dvd-rw, dvd-r",
        "tags_ukr":"оптичний привід, привід, dvd-rw, dvd-r",
        "category":"Оптические приводы",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Оптический привод CD-RW %s' % (model_name),
        "name_ukr":'Оптичний привід CD-RW %s' % (model_name),
        "tags_rus":"оптический привод, привод, dvd-rw, dvd-r",
        "tags_ukr":"оптичний привід, привід, dvd-rw, dvd-r",
        "category":"Оптические приводы",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Динамики, колонки %s' % (model_name),
        "name_ukr":'Динаміки, колонки %s' % (model_name),
        "tags_rus":"динамики, колонки, динамик, колонка, динамик ноутбука, колонка ноутбука, дифузор, звук, саунд, sound",
        "tags_ukr":"динаміки, колонки, динамік, колонка, динамік ноутбука, динаміки ноутбуку, колонка ноутбука, дифузор, звук, саунд, sound",
        "category":"Звуковые запчасти для портативных пк",
        "description_rus":"Динамики проверены на работоспособность - работают оба.",
        "description_ukr":"Динаміки перевірені на працездатність - працюють обидва.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Сабвуфер, динамик %s' % (model_name),
        "name_ukr":'Сабвуфер, динамік %s' % (model_name),
        "tags_rus":"динамики, колонки, динамик, колонка, динамик ноутбука, колонка ноутбука, дифузор, звук, саунд, sound",
        "tags_ukr":"динаміки, колонки, динамік, колонка, динамік ноутбука, динаміки ноутбуку, колонка ноутбука, дифузор, звук, саунд, sound",
        "category":"Звуковые запчасти для портативных пк",
        "description_rus":"Динамик проверен на работоспособность - работает.",
        "description_ukr":"Динамік перевірений на працездатність - працює.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата USB %s (юсб)' % (model_name),
        "name_ukr":'Плата USB %s (юсб)' % (model_name),
        "tags_rus":"плата, usb, юсб",
        "tags_ukr":"плата, usb, юсб",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата USB, audio %s (юсб, аудио)' % (model_name),
        "name_ukr":'Плата USB, audio %s (юсб, аудіо)' % (model_name),
        "tags_rus":"плата, usb, юсб, audio, аудио",
        "tags_ukr":"плата, usb, юсб, audio, аудіо",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата USB, audio, cardreader %s (юсб, аудио, кардридер)' % (model_name),
        "name_ukr":'Плата USB, audio, cardreader %s (юсб, аудіо, кардрідер)' % (model_name),
        "tags_rus":"плата, плата юсб, плата аудио, юсб, аудио, кардридер, USB, audio, cardreader",
        "tags_ukr":"плата, плата юсб, плата аудіо, юсб, аудіо, кардрідер, USB, audio, cardreader",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата audio %s (аудио)' % (model_name),
        "name_ukr":'Плата audio %s (аудіо)' % (model_name),
        "tags_rus":"audio, аудио, плата аудио, плата",
        "tags_ukr":"audio, аудіо, плата аудіо, плата",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата VGA %s (видео)' % (model_name),
        "name_ukr":'Плата VGA %s (відео)' % (model_name),
        "tags_rus":"плата, плата vga, vga, video, плата видео, плата video",
        "tags_ukr":"плата, плата vga, vga, video, плата відео, плата video",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата HDMI %s (видео)' % (model_name),
        "name_ukr":'Плата HDMI %s (відео)' % (model_name),
        "tags_rus":"плата, hdmi, видео",
        "tags_ukr":"плата, hdmi, відео",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата VGA, USB, audio, HDMI %s (видео, юсб, аудио)' % (model_name),
        "name_ukr":'Плата VGA, USB, audio, HDMI %s (відео, юсб, аудіо)' % (model_name),
        "tags_rus":"VGA, USB, audio, HDMI, видео, юсб, аудио",
        "tags_ukr":"VGA, USB, audio, HDMI, відео, юсб, аудіо",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата мультимедиа, кардридер %s (multimedia, cardreader)' % (model_name),
        "name_ukr":'Плата мультимедіа, кардрідер %s (multimedia, cardreader)' % (model_name),
        "tags_rus":"мультимедиа, кардридер, multimedia, cardreader",
        "tags_ukr":"мультимедіа, кардрідер, multimedia, cardreader",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Смарт-кардридер %s (Smart Card Reader Board)' % (model_name),
        "name_ukr":'Смарт-кардрідер %s (Smart Card Reader Board)' % (model_name),
        "tags_rus":"мультимедиа, кардридер, Smart Card Reader Board",
        "tags_ukr":"мультимедіа, кардрідер, Smart Card Reader Board",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата, шлейф мультимедийные кнопки %s (multimedia)' % (model_name),
        "name_ukr":'Плата, шлейф мультимедійні кнопки %s (multimedia)' % (model_name),
        "tags_rus":"плата, шлейф, мультимедиа кнопки, multimedia",
        "tags_ukr":"плата, шлейф, мультимедіа кнопки, multimedia",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата, шлейф, кнопка включения (питания) %s (вкл/выкл)' % (model_name),
        "name_ukr":'Плата, шлейф, кнопка включення (живлення) %s (вкл/викл)' % (model_name),
        "tags_rus":"плата, шлейф, кнопка, кнопка включения, вкл, выкл, вкл/выкл",
        "tags_ukr":"плата, шлейф, кнопка, кнопка включення, кнопка живлення, вкл, викл, вкл/викл",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата индикации %s' % (model_name),
        "name_ukr":'Плата індикації %s' % (model_name),
        "tags_rus":"плата индикации, плата, индикация",
        "tags_ukr":"плата індикації, плата, індикація",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Корзина, крепление HDD/SSD %s (caddy)' % (model_name),
        "name_ukr":'Корзина, кріплення HDD/SSD %s (caddy)' % (model_name),
        "tags_rus":"корзина, крепление HDD/SSD, caddy",
        "tags_ukr":"корзина, крепление HDD/SSD, caddy",
        "category":"Карманы для жестких дисков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Шлейф матрицы %s' % (model_name),
        "name_ukr":'Шлейф матриці %s' % (model_name),
        "tags_rus":"шлейф матрицы, шлейф, матрица",
        "tags_ukr":"шлейф матриці, шлейф, матриця",
        "category":"Шлейфы и разъемы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Разьем, адаптер, шлейф SATA HDD/SSD %s' % (model_name),
        "name_ukr":"Роз'єм, адаптер, шлейф SATA HDD/SSD %s" % (model_name),
        "tags_rus":"разьем, адаптер, шлейф, sata, hdd, ssd",
        "tags_ukr":"роз'єм, адаптер, шлейф, sata, hdd, ssd",
        "category":"Шлейфы и разъемы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Разъем, гнездо, кабель питания %s' % (model_name),
        "name_ukr":"Роз'єм, гніздо, кабель живлення %s" % (model_name),
        "tags_rus":"разъем, гнездо, кабель питания, кабель, питание",
        "tags_ukr":"роз'єм, гніздо, кабель живлення, кабель, живлення",
        "category":"Шлейфы и разъемы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Модуль Wi-Fi %s' % (model_name),
        "name_ukr":'Модуль Wi-Fi %s' % (model_name),
        "tags_rus":"модуль Wi-Fi, модуль, wi-fi, wifi",
        "tags_ukr":"модуль Wi-Fi, модуль, wi-fi, wifi",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Модуль блютуз, bluetooth %s' % (model_name),
        "name_ukr":'Модуль блютуз, bluetooth %s' % (model_name),
        "tags_rus":"модуль блютуз, bluetooth, модуль bluetooth",
        "tags_ukr":"модуль блютуз, bluetooth, модуль bluetooth",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'ВЕБ-камера %s (WEB-camera)' % (model_name),
        "name_ukr":'ВЕБ-камера %s (WEB-camera)' % (model_name),
        "tags_rus":"ВЕБ-камера, WEB-camera, камера, видео камера",
        "tags_ukr":"ВЕБ-камера, WEB-camera, камера, відео камера",
        "category":"Камеры для портативных пк",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Шлейф ВЕБ-камеры %s (WEB-camera)' % (model_name),
        "name_ukr":'Шлейф ВЕБ-камери %s (WEB-camera)' % (model_name),
        "tags_rus":"шлейф ВЕБ-камеры, шлейф, ВЕБ-камера, WEB-camera, камера, видео камера",
        "tags_ukr":"шлейф ВЕБ-камери, шлейф, ВЕБ-камера, WEB-camera, камера, відео камера",
        "category":"Шлейфы и разъемы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Инвертор матрицы %s' % (model_name),
        "name_ukr":'Інвертор матриці %s' % (model_name),
        "tags_rus":"инвертор матрицы, инвертор, матрица",
        "tags_ukr":"інвертор матриці, інвертор, матриця",
        "category":"Шлейфы и разъемы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Микрофон %s' % (model_name),
        "name_ukr":'Мікрофон %s' % (model_name),
        "tags_rus":"микрофон, мик, mic",
        "tags_ukr":"мікрофон, мік, mic",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Антенна Wi-Fi %s' % (model_name),
        "name_ukr":'Антена Wi-Fi %s' % (model_name),
        "tags_rus":"антенна wi-fi, антенна wifi, антенна, антена, антена wifi, антена wi-fi, wifi, wi-fi",
        "tags_ukr":"антена wi-fi, антена wifi, антена, wi-fi, wifi",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Оригинальная батарея %s' % (model_name),
        "name_ukr":'Оригінальна батарея %s' % (model_name),
        "tags_rus":"оригинальная батарея, оригинал батареи, батарея, оригинальный аккумулятор, аккумулятор",
        "tags_ukr":"оригіральна батарея, оригінал батареї, батарея, оригінальний акумулятор, акумулятор",
        "category":"Аккумуляторы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Батарея %s' % (model_name),
        "name_ukr":'Батарея %s' % (model_name),
        "tags_rus":"батарея, battery",
        "tags_ukr":"батарея, battery",
        "category":"Аккумуляторы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата LED %s' % (model_name),
        "name_ukr":'Плата LED %s' % (model_name),
        "tags_rus":"плата, плата led",
        "tags_ukr":"плата, плата led",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Модем %s' % (model_name),
        "name_ukr":'Модем %s' % (model_name),
        "tags_rus":"плата, плата led",
        "tags_ukr":"плата, плата led",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Матрица, экран, дисплей %s' % (model_name),
        "name_ukr":'Матриця, екран, дисплей %s' % (model_name),
        "tags_rus":"матрица, экран, дисплей",
        "tags_ukr":"матриця, екран, дисплей",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Разъем модема %s' % (model_name),
        "name_ukr":"Роз'єм модема %s" % (model_name),
        "tags_rus":"разъем модема, разъем, кабель модема, к модему",
        "tags_ukr":"роз'єм модема, роз'єм, кабель модема, до модему",
        "category":"Шлейфы и разъемы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Динамик левый %s' % (model_name),
        "name_ukr":'Динамік лівий %s' % (model_name),
        "tags_rus":"динамики, колонки, динамик, колонка, динамик ноутбука, колонка ноутбука, дифузор, звук, саунд, sound",
        "tags_ukr":"динаміки, колонки, динамік, колонка, динамік ноутбука, динаміки ноутбуку, колонка ноутбука, дифузор, звук, саунд, sound",
        "category":"Звуковые запчасти для портативных пк",
        "description_rus":"Динамик проверен на работоспособность - работает.",
        "description_ukr":"Динамік перевірений на працездатність - працює.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Динамик правый %s' % (model_name),
        "name_ukr":'Динамік правий %s' % (model_name),
        "tags_rus":"динамики, колонки, динамик, колонка, динамик ноутбука, колонка ноутбука, дифузор, звук, саунд, sound",
        "tags_ukr":"динаміки, колонки, динамік, колонка, динамік ноутбука, динаміки ноутбуку, колонка ноутбука, дифузор, звук, саунд, sound",
        "category":"Звуковые запчасти для портативных пк",
        "description_rus":"Динамик проверен на работоспособность - работает.",
        "description_ukr":"Динамік перевірений на працездатність - працює.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Накладка, на среднюю часть корпуса %s' % (model_name),
        "name_ukr":'Накладка, на середню частину корпуса %s' % (model_name),
        "tags_rus":"накладка, накладка на среднюю часть, топкейс, средняя часть, верхняя крышка, палмрест, palmrest, верхняя крышка базы",
        "tags_ukr":"накладка, накладка на середню частину, топкейс, средня частина, верхня кришка, палмрест, palmrest, верхня кришка бази",
        "category":"Части корпуса ноутбука",
        "description_rus":"Накладка вымыта и почищена.",
        "description_ukr":"Накладка вимита та почищена.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Топкейс, средняя часть %s (верхняя крышка)' % (model_name),
        "name_ukr":'Топкейс, середня частина %s (верхня кришка)' % (model_name),
        "tags_rus":"топкейс, средняя часть, верхняя крышка, палмрест, palmrest, верхняя крышка базы",
        "tags_ukr":"топкейс, средня частина, верхня кришка, палмрест, palmrest, верхня кришка бази",
        "category":"Части корпуса ноутбука",
        "description_rus":"Крышка вымыта и почищена.",
        "description_ukr":"Кришка вимита та почищена.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Топкейс, средняя часть с клавиатурой %s (верхняя крышка)' % (model_name),
        "name_ukr":'Топкейс, средня частина з клавіатурою %s (верхня кришка)' % (model_name),
        "tags_rus":"топкейс, средняя часть, клавиатура, palmrest, верхняя крышка базы",
        "tags_ukr":"топкейс, средня частина, клавіатура, palmrest, верхня кришка бази",
        "category":"Части корпуса ноутбука",
        "description_rus":"Крышка вымыта и почищена. Клавиатура проверена специальным прибором, все кнопки работают и не хрустят.",
        "description_ukr":"Кришка вимита та почищена. Клавіатура перевірена спеціальним прибором, всі кнопки працюють та не хрустят.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Топкейс, средняя часть с клавиатурой и тачпадом %s (верхняя крышка)' % (model_name),
        "name_ukr":'Топкейс, средня частина з клавіатурою та тачпадом %s (верхня кришка)' % (model_name),
        "tags_rus":"топкейс, средняя часть, клавиатура, palmrest, верхняя крышка базы, плата тачпад, тачпад, touchpad, трекпад",
        "tags_ukr":"топкейс, средня частина, клавіатура, palmrest, верхня кришка бази, плата тачпад, тачпад, touchpad, трекпад",
        "category":"Части корпуса ноутбука",
        "description_rus":"Крышка вымыта и почищена. Клавиатура проверена специальным прибором, все кнопки работают и не хрустят. Тачпад.",
        "description_ukr":"Кришка вимита та почищена. Клавіатура перевірена спеціальним прибором, всі кнопки працюють та не хрустят. Тачпад.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Топкейс, средняя часть с тачпадом %s (верхняя крышка)' % (model_name),
        "name_ukr":'Топкейс, средня частина та тачпад %s (верхня кришка)' % (model_name),
        "tags_rus":"топкейс, средняя часть, palmrest, верхняя крышка базы, плата тачпад, тачпад, touchpad, трекпад",
        "tags_ukr":"топкейс, средня частина, palmrest, верхня кришка бази, плата тачпад, тачпад, touchpad, трекпад",
        "category":"Части корпуса ноутбука",
        "description_rus":"Крышка вымыта и почищена. Тачпад.",
        "description_ukr":"Кришка вимита та почищена. Тачпад.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Направляющие матрицы %s' % (model_name),
        "name_ukr":'Направляючі матриці %s' % (model_name),
        "tags_rus":"направляющие матрицы, матрица, направляющие к матрице, направляющие экрана, стойки, стойки матрицы, стойки экрана",
        "tags_ukr":"направляючі матриці, матрица, направляючі до матриці, направляючі екрану, стійки, стійки матриці, стійки екрану",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Кнопка включения %s (вкл/выкл)' % (model_name),
        "name_ukr":'Кнопка включення (живлення) %s (вкл/викл)' % (model_name),
        "tags_rus":"кнопка включения, кнопка питания",
        "tags_ukr":"кнопка включення, кнопка живлення",
        "category":"Части корпуса ноутбука",
        "description_rus":"Кнопка вымыта и почищена.",
        "description_ukr":"Кнопка вимита та почищена.",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus": "Соединительная плата %s" % (model_name),
        "name_ukr": "З'єднуюча плата %s" % (model_name),
        "tags_rus": "плата, соединительная плата",
        "tags_ukr": "плата, з'єднуюча плата",
        "category": "Адаптеры и платы расширения портов",
        "description_rus": "Кнопка вымыта и почищена.",
        "description_ukr": "Кнопка вимита та почищена.",
        "flaw_rus": "",
        "flaw_ukr": "",
    },
    {
        "name_rus": "Шлейф нотбука %s" % (model_name),
        "name_ukr": "Шлейф ноутбуку %s" % (model_name),
        "tags_rus": "шлейф, кабель, провод, соединительный шлейф",
        "tags_ukr": "шлейф, кабель, провід, з'єднуючий шлейф",
        "category": "Части корпуса ноутбука",
        "description_rus": "Кнопка вымыта и почищена.",
        "description_ukr": "Кнопка вимита та почищена.",
        "flaw_rus": "",
        "flaw_ukr": "",
    },

]

# TODO

