from settings import model_name, model_state

detail_names = [
    {
        "name_rus":'Петли (левая, правая) %s %s' % (model_name, model_state),
        "name_ukr":'Петлі (ліва, права) %s %s' % (model_name, model_state),
        "tegs_rus":"петли, петля левая, петля правая, петля, петли матрицы, петли экрана, экран, матрица, крепление, часть корпуса,",
        "tegs_ukr":"петлі, петля ліва, петля права, петля, петлі матриці, петлі екрану, екран, матрица, кріплення, частина корпусу",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Петля левая (петли) %s %s' % (model_name, model_state),
        "name_ukr":'Петля ліва (петлі) %s %s' % (model_name, model_state),
        "tegs_rus":"петли, петля левая, петля, петли матрицы, петли экрана, экран, матрица, крепление, часть корпуса",
        "tegs_ukr":"петлі, петля ліва, петля, петлі матриці, петлі екрану, екран, матрица, кріплення, частина корпусу",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Петля правая (петли) %s %s' % (model_name, model_state),
        "name_ukr":'Петля права (петлі) %s %s' % (model_name, model_state),
        "tegs_rus":"петли, петля правая, петля, петли матрицы, петли экрана, экран, матрица, крепление, часть корпуса",
        "tegs_ukr":"петлі, петля права, петля, петлі матриці, петлі екрану, екран, матрица, кріплення, частина корпусу",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Нижняя часть корпуса %s %s (низ, дно, поддон, корыто)' % (model_name, model_state),
        "name_ukr":'Нижня частина корпуса %s %s (низ, дно, піддон, корито)' % (model_name, model_state),
        "tegs_rus":"нижняя крышка базы, нижняя часть корпуса, дно, днище, нижняя крышка базы, корито, нижний корпус, низ, поддон",
        "tegs_ukr":"нижня кришка бази, нижня частина корпуса, дно, днище, нижняя крышка базы, корито, нижній корпус, низ, піддон",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Крышка матрицы %s %s (крышка экрана, дисплея)' % (model_name, model_state),
        "name_ukr":'Кришка матриці %s %s (крышка екрану, дисплею)' % (model_name, model_state),
        "tegs_rus":"кришка матрицы, крышка экрана, корпус экрана, корпус, корпус ноутбука, задняя крышка экрана",
        "tegs_ukr":"кришка матриці, кришка екрану, корпус екрану, корпус, корпус ноутбука, корпус ноутбуку, задня кришка екрану",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Рамка матрицы (дисплея) %s %s' % (model_name, model_state),
        "name_ukr":'Рамка матриці (дисплею) %s %s' % (model_name, model_state),
        "tegs_rus":"рамка матрицы, рамка экрана, рамка дисплея",
        "tegs_ukr":"рамка матриці, рамка екрану, рамка дисплея, рамка дисплею",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Панель с кнопками %s %s' % (model_name, model_state),
        "name_ukr":'Панель з кнопками %s %s' % (model_name, model_state),
        "tegs_rus":"панель кнопок, верхняя панель, панель кнопки включения, панель, панель с кнопками, панель питания",
        "tegs_ukr":"панель кнопок, верхня панель, панель кнопки включення, панель, панель кнопки живлення, панель з кнопками, панель живлення",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Панель кнопки включения %s %s (вкл/выкл)' % (model_name, model_state),
        "name_ukr":'Панель кнопки включення (живлення) %s %s (вкл/викл)' % (model_name, model_state),
        "tegs_rus":"панель кнопки включения, панель, панель с кнопками, панель питания",
        "tegs_ukr":"панель кнопки включення, панель, панель кнопки живлення, панель з кнопками, панель живлення",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Заглушки (крышки) петель %s %s' % (model_name, model_state),
        "name_ukr":'Заглушки (крышки) петель %s %s' % (model_name, model_state),
        "tegs_rus":"колпачки, заглушки (крышки) петель, заглушки, заглушка, петли, петля",
        "tegs_ukr":"ковпачки, заглушки (крышки) петель, заглушки, заглушка, петлі, петля",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Накладка на петли %s %s' % (model_name, model_state),
        "name_ukr":'Накладка на петлі %s %s' % (model_name, model_state),
        "tegs_rus":"накладка, накладка на петли, петля, петли, колпачки, заглушки, заглушка",
        "tegs_ukr":"накладка, накладка на петлі, петля, петлі, ковпачки, заглушки, заглушка",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Тачпад (трекпад) %s %s (touchpad)' % (model_name, model_state),
        "name_ukr":'Тачпад (трекпад) %s %s (touchpad)' % (model_name, model_state),
        "tegs_rus":"Плата тачпад, тачпад, touchpad, трекпад",
        "tegs_ukr":"Плата тачпад, тачпад, touchpad, трекпад",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Панель тачпада (трекпада) %s %s' % (model_name, model_state),
        "name_ukr":'Панель тачпада (трекпада) %s %s' % (model_name, model_state),
        "tegs_rus":"панель тачпада, тачпад, touchpad",
        "tegs_ukr":"панель тачпада, тачпад, touchpad",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата, шлейф, кнопки тачпада %s %s (touchpad)' % (model_name, model_state),
        "name_ukr":'Плата, шлейф, кнопки тачпаду %s %s (touchpad)' % (model_name, model_state),
        "tegs_rus":"Плата, шлейф, кнопки тачпада, (touchpad)",
        "tegs_ukr":"Плата, шлейф, кнопки тачпаду, (touchpad)",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата, кнопки тачпада %s %s (touchpad)' % (model_name, model_state),
        "name_ukr":'Плата, кнопки тачпаду %s %s (touchpad)' % (model_name, model_state),
        "tegs_rus":"touchpad, плата, кнопки тачпада",
        "tegs_ukr":"touchpad, плата, кнопки тачпаду",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Сервисная крышка корпуса %s %s (заглушка)' % (model_name, model_state),
        "name_ukr":'Сервісна кришка корпусу %s %s (заглушка)' % (model_name, model_state),
        "tegs_rus":"сервисная крышка, крышка, заглушка, крышка корпуса",
        "tegs_ukr":"сервісна кришка, кришка, заглушка, кришка корпусу",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Сервисная крышка HDD/SSD %s %s' % (model_name, model_state),
        "name_ukr":'Сервісна кришка HDD/SSD %s %s' % (model_name, model_state),
        "tegs_rus":"сервисная крышка, крышка, hdd, ssd, hdd/ssd, заглушка",
        "tegs_ukr":"сервісна кришка, кришка, hdd, ssd, hdd/ssd, заглушка",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Сервисная крышка охлаждение %s %s' % (model_name, model_state),
        "name_ukr":'Сервісна кришка охолодження %s %s' % (model_name, model_state),
        "tegs_rus":"сервисная крышка, крышка, охлаждение, заглушка",
        "tegs_ukr":"сервісна кришка, кришка, охолодження, заглушка",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Клавиатура %s %s' % (model_name, model_state),
        "name_ukr":'Клавіатура %s %s' % (model_name, model_state),
        "tegs_rus":"клавиатура, клава, keyboard",
        "tegs_ukr":"клавіатура, клава, keyboard",
        "category":"Клавиатурные блоки для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Рамка клавиатуры %s %s' % (model_name, model_state),
        "name_ukr":'Рамка клавіатури %s %s' % (model_name, model_state),
        "tegs_rus":"рамка клавиатуры, рамка, клавиатура, клава, keyboard",
        "tegs_ukr":"рамка клавіатури, рамка, клавіатура, клава, keyboard",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Шлейф клавиатуры %s %s (keyboard)' % (model_name, model_state),
        "name_ukr":'Шлейф клавіатури %s %s (keyboard)' % (model_name, model_state),
        "tegs_rus":"шлейф клавиатуры, шлейф, клавиатура, клава, keyboard",
        "tegs_ukr":"шлейф клавіатури, шлейф, клавіатура, клава, keyboard",
        "category":"Шлейфы и разъемы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Топкейс, средняя часть %s %s (верхняя крышка)' % (model_name, model_state),
        "name_ukr":'Топкейс, средня частина %s %s (верхня кришка)' % (model_name, model_state),
        "tegs_rus":"топкейс, средняя часть, верхняя крышка, палмрест, palmrest, верхняя крышка базы",
        "tegs_ukr":"топкейс, средня частина, верхня кришка, палмрест, palmrest, верхня кришка бази",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Топкейс, средняя часть с клавиатурой %s %s (верхняя крышка)' % (model_name, model_state),
        "name_ukr":'Топкейс, средня частина з клавіатурою %s %s (верхня кришка)' % (model_name, model_state),
        "tegs_rus":"топкейс, средняя часть, клавиатура, palmrest, верхняя крышка базы",
        "tegs_ukr":"топкейс, средня частина, клавіатура, palmrest, верхня кришка бази",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Материнская плата %s %s (Системная плата)' % (model_name, model_state),
        "name_ukr":'Материнська плата %s %s (Системна плата)' % (model_name, model_state),
        "tegs_rus":"материнская плата, системная плата",
        "tegs_ukr":"материнська плата, системна плата",
        "category":"Материнские платы",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Кулер, вентилятор %s %s (FAN)' % (model_name, model_state),
        "name_ukr":'Кулер, вентилятор %s %s (FAN)' % (model_name, model_state),
        "tegs_rus":"кулер, вентилятор, fan",
        "tegs_ukr":"кулер, вентилятор, fan",
        "category":"Кулеры и системы охлаждения",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Система охлаждения, термотрубка %s DIS %s' % (model_name, model_state),
        "name_ukr":'Система охолодження, термотрубка %s DIS %s' % (model_name, model_state),
        "tegs_rus":"термотрубка, термотрубки, радиатор, система охлаждения, охлаждение, термотрубка системы охлаждения",
        "tegs_ukr":"термотрубка, термотрубки, радіатор, система охолодження, охолодження, термотрубка системи охолодження",
        "category":"Системы охлаждения для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Система охлаждения, термотрубка %s UMA %s' % (model_name, model_state),
        "name_ukr":'Система охолодження, термотрубка %s UMA %s' % (model_name, model_state),
        "tegs_rus":"термотрубка, термотрубки, радиатор, система охлаждения, охлаждение, термотрубка системы охлаждения",
        "tegs_ukr":"термотрубка, термотрубки, радіатор, система охолодження, охолодження, термотрубка системи охолодження",
        "category":"Системы охлаждения для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Оптический привод DVD-RW %s %s' % (model_name, model_state),
        "name_ukr":'Оптичний привід DVD-RW %s %s' % (model_name, model_state),
        "tegs_rus":"оптический привод, привод, dvd-rw, dvd-r",
        "tegs_ukr":"оптичний привід, привід, dvd-rw, dvd-r",
        "category":"Оптические приводы",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Оптический привод CD-RW %s %s' % (model_name, model_state),
        "name_ukr":'Оптичний привід CD-RW %s %s' % (model_name, model_state),
        "tegs_rus":"оптический привод, привод, dvd-rw, dvd-r",
        "tegs_ukr":"оптичний привід, привід, dvd-rw, dvd-r",
        "category":"Оптические приводы",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Динамики, колонки %s %s' % (model_name, model_state),
        "name_ukr":'Динаміки, колонки %s %s' % (model_name, model_state),
        "tegs_rus":"динамики, колонки, динамик, колонка, динамик ноутбука, колонка ноутбука, дифузор, звук, саунд, sound",
        "tegs_ukr":"динаміки, колонки, динамік, колонка, динамік ноутбука, динаміки ноутбуку, колонка ноутбука, дифузор, звук, саунд, sound",
        "category":"Звуковые запчасти для портативных пк",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Сабвуфер, динамик %s %s' % (model_name, model_state),
        "name_ukr":'Сабвуфер, динамік %s %s' % (model_name, model_state),
        "tegs_rus":"динамики, колонки, динамик, колонка, динамик ноутбука, колонка ноутбука, дифузор, звук, саунд, sound",
        "tegs_ukr":"динаміки, колонки, динамік, колонка, динамік ноутбука, динаміки ноутбуку, колонка ноутбука, дифузор, звук, саунд, sound",
        "category":"Звуковые запчасти для портативных пк",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата USB %s %s (юсб)' % (model_name, model_state),
        "name_ukr":'Плата USB %s %s (юсб)' % (model_name, model_state),
        "tegs_rus":"плата, usb, юсб",
        "tegs_ukr":"плата, usb, юсб",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата USB, audio %s %s (юсб, аудио)' % (model_name, model_state),
        "name_ukr":'Плата USB, audio %s %s (юсб, аудіо)' % (model_name, model_state),
        "tegs_rus":"плата, usb, юсб, audio, аудио",
        "tegs_ukr":"плата, usb, юсб, audio, аудіо",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата USB, audio, cardreader %s %s (юсб, аудио, кардридер)' % (model_name, model_state),
        "name_ukr":'Плата USB, audio, cardreader %s %s (юсб, аудіо, кардрідер)' % (model_name, model_state),
        "tegs_rus":"плата, плата юсб, плата аудио, юсб, аудио, кардридер, USB, audio, cardreader",
        "tegs_ukr":"плата, плата юсб, плата аудіо, юсб, аудіо, кардрідер, USB, audio, cardreader",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата audio %s %s (аудио)' % (model_name, model_state),
        "name_ukr":'Плата audio %s %s (аудіо)' % (model_name, model_state),
        "tegs_rus":"audio, аудио, плата аудио, плата",
        "tegs_ukr":"audio, аудіо, плата аудіо, плата",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата VGA %s %s (видео)' % (model_name, model_state),
        "name_ukr":'Плата VGA %s %s (відео)' % (model_name, model_state),
        "tegs_rus":"плата, плата vga, vga, video, плата видео, плата video",
        "tegs_ukr":"плата, плата vga, vga, video, плата відео, плата video",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата HDMI %s %s (видео)' % (model_name, model_state),
        "name_ukr":'Плата HDMI %s %s (відео)' % (model_name, model_state),
        "tegs_rus":"плата, hdmi, видео",
        "tegs_ukr":"плата, hdmi, відео",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата VGA, USB, audio, HDMI %s %s (видео, юсб, аудио)' % (model_name, model_state),
        "name_ukr":'Плата VGA, USB, audio, HDMI %s %s (відео, юсб, аудіо)' % (model_name, model_state),
        "tegs_rus":"VGA, USB, audio, HDMI, видео, юсб, аудио",
        "tegs_ukr":"VGA, USB, audio, HDMI, відео, юсб, аудіо",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата мультимедиа, кардридер %s %s (multimedia, cardreader)' % (model_name, model_state),
        "name_ukr":'Плата мультимедіа, кардрідер %s %s (multimedia, cardreader)' % (model_name, model_state),
        "tegs_rus":"мультимедиа, кардридер, multimedia, cardreader",
        "tegs_ukr":"мультимедіа, кардрідер, multimedia, cardreader",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата, шлейф мультимедийные кнопки %s %s (multimedia)' % (model_name, model_state),
        "name_ukr":'Плата, шлейф мультимедійні кнопки %s %s (multimedia)' % (model_name, model_state),
        "tegs_rus":"плата, шлейф, мультимедиа кнопки, multimedia",
        "tegs_ukr":"плата, шлейф, мультимедіа кнопки, multimedia",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата, шлейф, кнопка включения (питания) %s %s (вкл/выкл)' % (model_name, model_state),
        "name_ukr":'Плата, шлейф, кнопка включення (живлення) %s %s (вкл/викл)' % (model_name, model_state),
        "tegs_rus":"плата, шлейф, кнопка, кнопка включения, вкл, выкл, вкл/выкл",
        "tegs_ukr":"плата, шлейф, кнопка, кнопка включення, кнопка живлення, вкл, викл, вкл/викл",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата индикации %s %s' % (model_name, model_state),
        "name_ukr":'Плата індикації %s %s' % (model_name, model_state),
        "tegs_rus":"плата индикации, плата, индикация",
        "tegs_ukr":"плата індикації, плата, індикація",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Корзина, крепление HDD/SSD %s %s (caddy)' % (model_name, model_state),
        "name_ukr":'Корзина, кріплення HDD/SSD %s %s (caddy)' % (model_name, model_state),
        "tegs_rus":"корзина, крепление HDD/SSD, caddy",
        "tegs_ukr":"корзина, крепление HDD/SSD, caddy",
        "category":"Карманы для жестких дисков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Шлейф матрицы %s %s' % (model_name, model_state),
        "name_ukr":'Шлейф матриці %s %s' % (model_name, model_state),
        "tegs_rus":"шлейф матрицы, шлейф, матрица",
        "tegs_ukr":"шлейф матриці, шлейф, матриця",
        "category":"Шлейфы и разъемы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Разьем, адаптер, шлейф SATA HDD/SSD %s %s' % (model_name, model_state),
        "name_ukr":"Роз'єм, адаптер, шлейф SATA HDD/SSD %s %s" % (model_name, model_state),
        "tegs_rus":"разьем, адаптер, шлейф, sata, hdd, ssd",
        "tegs_ukr":"роз'єм, адаптер, шлейф, sata, hdd, ssd",
        "category":"Шлейфы и разъемы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Разъем, гнездо, кабель питания %s %s' % (model_name, model_state),
        "name_ukr":"Роз'єм, гніздо, кабель живлення %s %s" % (model_name, model_state),
        "tegs_rus":"разъем, гнездо, кабель питания, кабель, питание",
        "tegs_ukr":"роз'єм, гніздо, кабель живлення, кабель, живлення",
        "category":"Шлейфы и разъемы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Модуль Wi-Fi %s %s' % (model_name, model_state),
        "name_ukr":'Модуль Wi-Fi %s %s' % (model_name, model_state),
        "tegs_rus":"модуль Wi-Fi, модуль, wi-fi, wifi",
        "tegs_ukr":"модуль Wi-Fi, модуль, wi-fi, wifi",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Модуль блютуз, bluetooth %s %s' % (model_name, model_state),
        "name_ukr":'Модуль блютуз, bluetooth %s %s' % (model_name, model_state),
        "tegs_rus":"модуль блютуз, bluetooth, модуль bluetooth",
        "tegs_ukr":"модуль блютуз, bluetooth, модуль bluetooth",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'ВЕБ-камера %s %s (WEB-camera)' % (model_name, model_state),
        "name_ukr":'ВЕБ-камера %s %s (WEB-camera)' % (model_name, model_state),
        "tegs_rus":"ВЕБ-камера, WEB-camera, камера, видео камера",
        "tegs_ukr":"ВЕБ-камера, WEB-camera, камера, відео камера",
        "category":"Камеры для портативных пк",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Шлейф ВЕБ-камеры %s %s (WEB-camera)' % (model_name, model_state),
        "name_ukr":'Шлейф ВЕБ-камери %s %s (WEB-camera)' % (model_name, model_state),
        "tegs_rus":"шлейф ВЕБ-камеры, шлейф, ВЕБ-камера, WEB-camera, камера, видео камера",
        "tegs_ukr":"шлейф ВЕБ-камери, шлейф, ВЕБ-камера, WEB-camera, камера, відео камера",
        "category":"Шлейфы и разъемы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Инвертор матрицы %s %s' % (model_name, model_state),
        "name_ukr":'Інвертор матриці %s %s' % (model_name, model_state),
        "tegs_rus":"инвертор матрицы, инвертор, матрица",
        "tegs_ukr":"інвертор матриці, інвертор, матриця",
        "category":"Шлейфы и разъемы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Микрофон %s %s' % (model_name, model_state),
        "name_ukr":'Мікрофон %s %s' % (model_name, model_state),
        "tegs_rus":"микрофон, мик, mic",
        "tegs_ukr":"мікрофон, мік, mic",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Антенна Wi-Fi %s %s' % (model_name, model_state),
        "name_ukr":'Антена Wi-Fi %s %s' % (model_name, model_state),
        "tegs_rus":"антенна wi-fi, антенна wifi, антенна, антена, антена wifi, антена wi-fi, wifi, wi-fi",
        "tegs_ukr":"антена wi-fi, антена wifi, антена, wi-fi, wifi",
        "category":"Адаптеры и платы расширения портов",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Оригинальная батарея %s %s' % (model_name, model_state),
        "name_ukr":'Оригінальна батарея %s %s' % (model_name, model_state),
        "tegs_rus":"оригинальная батарея, оригинал батареи, батарея, оригинальный аккумулятор, аккумулятор",
        "tegs_ukr":"оригіральна батарея, оригінал батареї, батарея, оригінальний акумулятор, акумулятор",
        "category":"Аккумуляторы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Батарея %s %s' % (model_name, model_state),
        "name_ukr":'Батарея %s %s' % (model_name, model_state),
        "tegs_rus":"батарея, battery",
        "tegs_ukr":"батарея, battery",
        "category":"Аккумуляторы для ноутбуков",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
    {
        "name_rus":'Плата LED %s %s' % (model_name, model_state),
        "name_ukr":'Плата LED %s %s' % (model_name, model_state),
        "tegs_rus":"плата, плата led",
        "tegs_ukr":"плата, плата led",
        "category":"Части корпуса ноутбука",
        "description_rus":"",
        "description_ukr":"",
        "flaw_rus":"",
        "flaw_ukr":"",
    },
]